### ISSUE TITLE
FHIR OpenAPI / Swagger Generation

### ISSUE THREAD

**Issue by neothoms** [microsoft/fhir-codegen#98]
Hi,

 I am trying to find a way to get a full OpenAPI / Swagger definition file for an Azure FHIR API Service.
 I asked the azure support and they have redirected to this project.

 I have tried to generate a swagger file from R4 definition but I am having difficulties.
 If I try with the R4 from package with this command : 
`fhir-codegen-cli.exe --load-r4 latest --fhir-spec-directory c:\temp\fhirR4 --language OpenApi --output-path c:\temp\FhirR4.json`

I can see that there is an error "duplicate property found : Laterality" and the output file seems missing objects like Account

```
Starting FhirCacheService...
 <<< using cache directory: C:\Users\sthomas\.fhir
 << cache contains 2 packges
Starting FhirManager...
GetPackageVersionsAndUrls <<< Package http://packages2.fhir.org/packages/hl7.fhir.r4.expansions contains NO versions
LoadCached <<< Loaded and Parsed FHIR R4 with 0 errors and 1 warnings

Errors (only able to pass with manual code changes)
Warnings (able to pass, but should be reviewed)
 - CodeSystem SNOMED_CT (snomedct): Duplicate proprety found: Laterality
Loaded hl7.fhir.r4.core#latest as hl7.fhir.r4.core version 4.0.1
+ c:\code\temp\R4.json
Done! Loading: 4.413s, Total: 5.025s
```

But If I try from the api fhir Service Url there is another error and there is no output : 
```
fhir-codegen-cli.exe --fhir-server-url https://fhirwspocpublic-apiservice.fhir.azurehealthcareapis.com/metadata --language OpenAPI --output-path c:\code\temp\FHIRR4_cli.json
Starting FhirCacheService...
 <<< using cache directory: C:\Users\sthomas\.fhir
 << cache contains 2 packges
Starting FhirManager...
Requesting metadata from https://fhirwspocpublic-apiservice.fhir.azurehealthcareapis.com/metadata...
Connected to https://fhirwspocpublic-apiservice.fhir.azurehealthcareapis.com/metadata, FHIR version: 4.0.1
Server Information from https://fhirwspocpublic-apiservice.fhir.azurehealthcareapis.com/metadata:
            FHIR Version: 4.0.1
           Software Name: Azure Healthcare APIs
        Software Version: 2.3.60
            Release Date:
             Description:
               Resources: 146
GetPackageVersionsAndUrls <<< Package http://packages2.fhir.org/packages/hl7.fhir.r4.expansions contains NO versions
LoadCached <<< Loaded and Parsed FHIR R4 with 0 errors and 1 warnings

Errors (only able to pass with manual code changes)
Warnings (able to pass, but should be reviewed)
 - CodeSystem SNOMED_CT (snomedct): Duplicate proprety found: Laterality
Loaded hl7.fhir.r4.core#latest as hl7.fhir.r4.core version 4.0.1
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Health.Fhir.SpecManager.Models.FhirServerInfo..ctor(FhirServerInfo source, FhirVersionInfo info) in C:\code\fhir-codegen\src\Microsoft.Health.Fhir.SpecManager\Models\FhirServerInfo.cs:line 139
   at Microsoft.Health.Fhir.SpecManager.Manager.Exporter.Export(FhirVersionInfo sourceFhirInfo, FhirServerInfo sourceServerInfo, ILanguage exportLanguage, ExporterOptions options, String outputPath, Boolean isPartOfBatch) in C:\code\fhir-codegen\src\Microsoft.Health.Fhir.SpecManager\Manager\Exporter.cs:line 136
   at FhirCodegenCli.Program.Process(String fhirSpecDirectory, String outputPath, Boolean verbose, Boolean offlineMode, String language, String exportKeys, String loadR2, String loadR3, String loadR4, String loadR4B, String loadR5, String languageOptions, Boolean officialExpansionsOnly, String fhirServerUrl, Boolean includeExperimental, String exportTypes, String extensionSupport, Boolean languageHelp, String packageDirectory, String packages, String ciBranch, String languageInputDir) in C:\code\fhir-codegen\src\fhir-codegen-cli\Program.cs:line 544
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass26_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass24_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__23_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__8_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__7_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

Can you please help me on what I am doing wrong  ?

**Comment by GinoCanessa** [comment]
Hi @neothoms, I just merged a PR that addresses the issue when passing in the server URL.  It was a regression caused by some internal restructuring.

I tested the command you provided and it generates the correct file on my local machine.  If you need anything else, please let us know.

Thanks!

**Comment by neothoms** [comment]
Thanks a lot.
I have two following questions.
 I can not see any patch methods. Is it normal ?

 I can still see a warning "Duplicate property found: Laterality"
```

 <<< using cache directory: C:\Users\sthomas\.fhir
 << cache contains 2 packges
Starting FhirManager...
Requesting metadata from https://fhirwspocpublic-apiservice.fhir.azurehealthcareapis.com/metadata...
Connected to https://fhirwspocpublic-apiservice.fhir.azurehealthcareapis.com/metadata, FHIR version: 4.0.1
Server Information from https://fhirwspocpublic-apiservice.fhir.azurehealthcareapis.com/metadata:
            FHIR Version: 4.0.1
           Software Name: Azure Healthcare APIs
        Software Version: 2.3.60
            Release Date:
             Description:
               Resources: 146
GetPackageVersionsAndUrls <<< Failed to get package info: BadGateway http://packages2.fhir.org/packages/hl7.fhir.r4.core
GetPackageVersionsAndUrls <<< Failed to get package info: BadGateway http://packages2.fhir.org/packages/hl7.fhir.r4.expansions
LoadCached <<< Loaded and Parsed FHIR R4 with 0 errors and 1 warnings

Errors (only able to pass with manual code changes)
Warnings (able to pass, but should be reviewed)
 - CodeSystem SNOMED_CT (snomedct): Duplicate proprety found: Laterality
Loaded hl7.fhir.r4.core#latest as hl7.fhir.r4.core version 4.0.1
+ c:\code\temp\R4.json
Done! Loading: 54.692s, Total: 55.726s
```

**Comment by GinoCanessa** [comment]
Looks like PATCH support was incomplete - I am working through it now, but I also have some improvements to the search mechanisms that should be improved, based on new guidance in the spec.

I will add a comment when the next update is ready, though it will likely not be today.

The other messages you are seeing are for FHIR spec development and can be ignored (there is an item on my queue to hide them by default).  For reference, the package download messages are indicating an issue with the backup FHIR package server and the 'laterality' issue is notifying about a typo (duplicate record) in the one of the base specification expansions.

**Comment by GinoCanessa** [comment]
Hi @neothoms , just wanted to let you know that I have pushed an update.  There is a remaining known issue for operations not being listed - the capability statements do not contain enough information to list them and I have not done the work to resolve definitions yet.

Otherwise I will note that the 'default' configuration is resulting in a larger file - if you run into the limits on APIM, you can use the various language options to reduce the size (e.g., excluding summaries or descriptions, reducing the allowed response codes, minifying the file, etc.).

Cheers!

**Comment by neothoms** [comment]
Hi @GinoCanessa, were you able to advance on this issue please ?
We need quickly to know if the integration of fhir on Apim is feasible (ETA october).

If it is not, we need to launch a project to implement a temporary redirection with an app gateway or another service that will take apim place until open api is available.

Thanks in advance for your time

**Comment by GinoCanessa** [comment]
Hi @neothoms - I believe everything you need should be working out of the `dev` branch now.  I am still working on documentation and updating the UI to make it easier to use, but it should be unblocked.

I ended up needing to rewrite the OpenAPI internals to get operation support working, and the team at Firely was good enough to run through testing and fix a few issues I introduced during the process.

The language options have changed, so (based on your initial command line), I would start with something like:
`fhir-codegen-cli.exe --fhir-server-url http://{your server url} --language OpenApi --language-options OpenApi|SingleResponses=true|Metadata=true|SchemaLevel=names|FileFormat=json|Minify=true --output-path c:\temp\FhirR4.json`

Until the documentation gets updated, you can see all the options from the CLI using the `--language-help` option.  I am including the list below for convenience.

Please let me know if you run into any issues.


>          - OpenApiVersion
>                 Open API version to use (2|3).
>         - FileFormat
>                 File format to export (json|yaml).
>         - Title
>                 Title to use in the Info section, defaults to 'FHIR {FhirSequence}:{VersionString}'.
>         - Version
>                 Version number to use in the OpenAPI file, defaults to '{FHIR Version}'.
>         - SchemaLevel
>                 How much schema to include (none|names|detailed).
>         - SchemaStyle
>                 How schemas should be built (references|inline).
>         - MaxRecursions
>                 Maximum depth to expand recursions (0).
>         - FhirMime
>                 Which FHIR MIME types to support (capabilities|json|xml|common|turtle|all).
>         - PatchMime
>                 Which FHIR Patch types to support (capabilities|json|xml|fhirMime|all).
>         - SearchSupport
>                 Supported search methods (both|get|post|none).
>         - IncludeSearchParams
>                 If search parameters should be included in the definitions (true|false).
>         - SearchPostParams
>                 Where search params should appear in post-based search (body|query|both|none).
>         - ConsolidateSearchParams
>                 If search parameters should be consolidated (true|false).
>         - OperationSupport
>                 Supported Operation calling styles (both|post|get|none).
>         - UpdateCreate
>                 If update can commit to a new identity (capabilities|false|true).
>         - ConditionalCreate
>                 If the server allows/uses conditional create (capabilities|false|true).
>         - ConditionalRead
>                 Conditional read policy (capabilities|not-supported|modified-since|not-match|full-support).
>         - ConditionalUpdate
>                 If the server allows/uses conditional update (capabilities|false|true).
>         - ConditionalPatch
>                 If the server allows/uses conditional patch (capabilities|false|true).
>         - ConditionalDelete
>                 How conditional delete is supported (capabilities|not-supported|single|multiple).
>         - History
>                 If _history GET operations should be included (false|true).
>         - Metadata
>                 If the JSON should include a link to /metadata (true|false).
>         - BundleOperations
>                 If the generator should include /Bundle, etc. (true|false).
>         - ReadOnly
>                 If the output should only contain GET operations (false|true).
>         - WriteOnly
>                 If the output should only contain POST/PUT/DELETE operations (false|true).
>         - Descriptions
>                 If properties should include descriptions (true|false).
>         - DescriptionMaxLen
>                 Maximum length of descriptions, if being validated (60).
>         - DescriptionValidation
>                 If descriptions are required and should be validated (false|true).
>         - ExpandProfiles
>                 If types should expand based on allowed profiles (true|false).
>         - ExpandReferences
>                 If types should expand through references (true|false).
>         - Minify
>                 If the output JSON should be minified (false|true).
>         - IdConvention
>                 Naming convention to use for OpenAPI ids (pascal|camel|upper|lower).
>         - HttpCommonParams
>                 Comma-separated list of query params common to all ops, '-' for none (_format,_pretty).
>         - HttpReadParams
>                 Comma-separated list of query params common to reads, '-' for none (_elements,_summary).
>         - SearchResultParams
>                 Comma-separated list of search result params, '-' for none (_contained,_count,_graph,_include,_revinclude,_score,_sort,_total).
>         - SearchCommonParams
>                 Comma-separated list of common search params, '-' for none (_content,_filger,_id,_in,_language,_lastUpdated,_list,_profile,_query,_security,_source,_tag,_text).
>         - HistoryParams
>                 Comma-separated list of allowed history params, '-' for none (_count,_since,_at,_list,_sort).
>         - RemoveUncommonFields
>                 If the generator should remove some uncommon fields (false|true).
>         - SingleResponses
>                 If operations should only include a single response (false|true).
>         - Summaries
>                 If responses should include summaries (true|false).
>         - IncludeHeaders
>                 If the output should include HTTP Headers (false|true).
>         - MultiFile
>                 If the export should split contents across multiple files (false|true).

**Comment by newSebastienTHOMAS** [comment]
Thanks a lot.
I am not working on FHIR project anymore but I have transmitted the info to my collegues.

**Comment by neothoms** [comment]
Thanks a lot.
I am not working on FHIR project anymore but I have transmitted the info to my collegues.

**Comment by nrobert** [comment]
Following the topic ( @neothoms  was working for our client). Thanks @GinoCanessa  for your efforts
